### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ildarkhasanshin** [matiaspub/BitrixHelp#1]
Traceback (most recent call last):
File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/opt/sublime_text/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/ildar/.config/sublime-text-3/Packages/BitrixHelp/BitrixHelp.py", line 8, in run
    pages = settings.get('pages').get(it)
AttributeError: 'NoneType' object has no attribute 'get'

st 3126
ubuntu 16.10

**Comment by ildarkhasanshin** [comment]
fix https://github.com/matiaspub/BitrixHelp/pull/2/commits/7a01640dcaa183b810204edf4e2e3dabacedc8f6

**Comment by ildarkhasanshin** [comment]
merged
